package com.vic.recompo.domain.model

enum class Sexo { HOMBRE, MUJER }

enum class SlotComida { DESAYUNO, ALMUERZO, COMIDA, MERIENDA, CENA }

enum class GrupoMuscular {
    PECHO, ESPALDA, DORSAL,
    HOMBRO, HOMBRO_FRONTAL, HOMBRO_LATERAL, HOMBRO_POSTERIOR,
    BICEPS, TRICEPS, ANTEBRAZO,
    CUADRICEPS, ISQUIOTIBIALES, ISQUIOS, GLUTEO,
    PANTORRILLA, GEMELOS,
    CORE, TRAPECIO, LUMBAR, FULL_BODY
}

enum class PatronMovimiento {
    EMPUJE_HORIZONTAL, EMPUJE_INCLINADO, EMPUJE_VERTICAL,
    TIRON_HORIZONTAL, TIRON_VERTICAL,
    BISAGRA, BISAGRA_CADERA, BISAGRA_EXPLOSIVA,
    SENTADILLA, LUNGES, UNILATERAL,
    EXTENSION_CADERA, EXPLOSIVO,
    AISLAMIENTO,
    ESTABILIZACION, FLEXION_CORE, ROTACION_CORE,
    CORE, CARDIO
}

enum class TipoSesion { A, B, C }

enum class EstadoSesion { PLANIFICADA, EN_CURSO, COMPLETADA, OMITIDA }

enum class OrigenSesion { SEED, IA, MANUAL }

enum class TipoConversacion { NUTRICIONAL, ENTRENO }

enum class RolMensaje { USER, ASSISTANT }
