package com.vic.recompo.domain.model

enum class Sexo { HOMBRE, MUJER }

enum class SlotComida { DESAYUNO, ALMUERZO, COMIDA, MERIENDA, CENA }

enum class GrupoMuscular {
    PECHO, ESPALDA, DORSAL,
    HOMBRO, HOMBRO_FRONTAL, HOMBRO_LATERAL, HOMBRO_POSTERIOR,
    BICEPS, TRICEPS, ANTEBRAZO,
    CUADRICEPS, ISQUIOTIBIALES, ISQUIOS, GLUTEO,
    PANTORRILLA, GEMELOS,
    CORE, TRAPECIO, LUMBAR, FULL_BODY
}

enum class PatronMovimiento {
    EMPUJE_HORIZONTAL, EMPUJE_INCLINADO, EMPUJE_VERTICAL,
    TIRON_HORIZONTAL, TIRON_VERTICAL,
    BISAGRA, BISAGRA_CADERA, BISAGRA_EXPLOSIVA,
    SENTADILLA, LUNGES, UNILATERAL,
    EXTENSION_CADERA, EXPLOSIVO,
    AISLAMIENTO,
    ESTABILIZACION, FLEXION_CORE, ROTACION_CORE,
    CORE, CARDIO
}

// TipoSesion es ahora una entidad Room (data/db/entity/TipoSesion.kt)

enum class EstadoSesion { PREPARADA, EN_CURSO, COMPLETADA, OMITIDA }

enum class EstadoSerie { COMPLETADA, OMITIDA }

enum class MotivoOmision { TIEMPO, INNECESARIA, MOLESTIA }

enum class OrigenSesion { SEED, IA, MANUAL }

enum class TipoConversacion { NUTRICIONAL, ENTRENO }

enum class RolMensaje { USER, ASSISTANT }

enum class FuncionIA { PARSEO_COMIDA, GENERACION_SESION, CHAT, DESCOMPOSICION_COMIDA }

enum class ProveedorIA { CLAUDE_NATIVO, OPENROUTER }

enum class Fiabilidad { VALIDADO, ESTIMADO }
